---
title: "COVID-19 Maps by UCI Statistics"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<br>
<br>

### Number of COVID-19 cases mapped to OC zip codes


```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.align = "center",
  message = FALSE,
  warning = FALSE
)
```


```{r delete-old-map-docs}
if(dir.exists("docs/images")) {
  unlink("docs/images", recursive = TRUE)
}
```


```{r libraries}
source("code/map-functions.R")
```


```{r generate-cases-map}
cases_plot_data <- read.csv("data/cases_map_data.csv")[, -1]
cases_plot_data$zip <- as.character(cases_plot_data$zip)
cases_legend_label <- readLines("data/cases_legend_label.txt")
max_date_in_data <- readLines("data/max_date_in_map_data.txt")

date_seq <- zoo::as.yearmon(
  seq(as.Date("2020-03-01"), as.Date(max_date_in_data), by = "months"), 
  "%m/%Y"
)

gen_map_gif(
  plot_data = cases_plot_data, 
  socal_shp_file = "data/shape-files/socal-zip/Zipcode_boundary_scag_2009.shp", 
  ca_shp_file = "data/shape-files/ca-counties/cnty19_1.shp", 
  legend_label = cases_legend_label, 
  month_seq = date_seq, 
  var_type = "cases"
)
```


```{r display-cases-map}
htmltools::includeHTML("docs/cases-map-gif.html")
```


Data provided by the [Orange County Health Care Agency](https://www.ochealthinfo.com).  
Most recent date in data used was `r max_date_in_data`.  
Last updated on `r lubridate::today()`.
