---
title: "COVID-19 Trends by UCI Statistics"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.retina = 2)
library(tidyverse)
library(lubridate)
library(scales)
library(TTR)
library(glue)
library(ggtext)
library(ckanr) # library to interact with CA Gov. Public Health Portal
library(cowplot)

# connect to CKAN instance
ckanr_setup(url="https://data.ca.gov")
ckan <- ckanr::src_ckan("https://data.ca.gov")

# get resources
resources <- rbind(resource_search("name:covid-19", as = "table")$results,
             resource_search("name:hospitals by county", as = "table")$results)

resource_ids <- list(cases = resources$resource_id[resources$name == "COVID-19 Cases"],
                     tests = resources$resource_id[resources$name == "COVID-19 Testing"],
                     hosp = resources$resource_id[resources$name == "Hospitals By County"])

# pull resources into data frames (adds extra cols _id and _full_text)
cases <- tbl(src = ckan$con, from = resource_ids$cases) %>%
  as_tibble( )%>%
  select(-starts_with("_")) %>% 
  mutate(date = as.Date(date))

tests <- tbl(src = ckan$con, from = resource_ids$test) %>%
  as_tibble() %>%
  select(-starts_with("_")) %>% 
  mutate(date = as.Date(date))

hosp <- tbl(src = ckan$con, from = resource_ids$hosp) %>%
  as_tibble() %>%
  select(-starts_with("_")) %>% 
  mutate(date = as.Date(todays_date)) %>% 
  select(-todays_date)

county_pop <- read_csv("data/county_pop.csv") %>% rename_all(str_to_lower)

# stay at home order start and end dates
sah_start <- ymd("2020-03-19")
sah_end <- ymd("2020-05-04")
```



```{r tidy data, message=FALSE}
# Data Processing Options
counties_of_interest <- c("San Diego",  "Los Angeles",  "Orange", "Alameda", "Santa Clara")

per_n_people <- 1e6 # denominator for reporting counts (e.g, per million people)
ma_n <- 7 # moving average window length in days

# Tidy Data
hosp_tidy <- hosp %>%
  filter(county %in% counties_of_interest) %>% 
  pivot_longer(cols = -c(date, county)) %>% 
  drop_na() %>% 
  left_join(county_pop) %>% 
  arrange(county, date)

cases_tidy <- cases %>% 
  filter(county %in% counties_of_interest) %>% 
  pivot_longer(cols = -c(date, county)) %>% 
  drop_na() %>% 
  left_join(county_pop) %>% 
  arrange(county, date)


# Theme options
theme_set(theme_bw(base_size = 14) +
            theme(legend.position = "bottom",
                  legend.title = element_text(size = 12)))

cbPalette <- c("#56B4E9", "#009E73", "#E69F00", "#CC79A7", "#0072B2")

sah_alpha <- 0.2

gglayers = list(
  geom_line(size = 1.5),
  scale_color_manual(name = "County", values = cbPalette),
  scale_x_date(name = "Date",
               breaks = "14 day",
               date_labels = "%b %d",
               expand = expansion(add=c(0,7))),
  scale_y_continuous(label = comma)
)

watermark <- function(plt) ggdraw(plt) + draw_label("UC Irvine COVID Awareness Group", color = "#0064A4", alpha=0.4, size = 15, angle = 0, x=0.20, y=0.85, hjust = 0, vjust = 0)
# Could also use stamp function
# stamp(plot1, label = "DRAFT", color = "red")
```

```{r make plots}
# Hospitalizations
hospitalizations_plot_data <- hosp_tidy %>% 
  filter(name == "hospitalized_covid_patients") %>% 
  group_by(county) %>%
  mutate(value = runMean(value, ma_n)) %>% 
  drop_na()

hospitalizations_plot <- hospitalizations_plot_data %>% 
  ggplot(aes(date, value / population * per_n_people, group = county, color = county)) +
  ggtitle(glue("Hospitalized Patients with COVID-19 <span style='font-size:14pt'>({ma_n} Day Moving Average)</span>")) +
          #subtitle = glue("{ma_n} Day Moving Average")) 
  theme(
    plot.title = element_markdown()
  ) +
  gglayers +
  ylab(glue("Hospitalized Patients with COVID-19\nper {comma(per_n_people)} People")) +
  annotate("rect",
           xmin = if_else(min(hospitalizations_plot_data$date) < sah_start,
                          sah_start,
                          min(hospitalizations_plot_data$date)),
           xmax = sah_end, ymin = -Inf, ymax = Inf, alpha = sah_alpha) +
    annotate("text", y = 175, x = sah_end+8, label = "Stay at Home\nOrder Ended")

# ICU Occupancy
icu_plot_data <- hosp_tidy %>% 
  filter(name %in% c("icu_covid_confirmed_patients", "icu_suspected_covid_patients")) %>% 
  group_by(county, date, population) %>% 
  summarize(value = sum(value)) %>% 
  group_by(county) %>%
  mutate(value = runMean(value, ma_n)) %>%
  drop_na()  %>%
filter(date >= min(hospitalizations_plot_data$date)) 

icu_plot <- icu_plot_data %>% 
  ggplot(aes(date, value / population * per_n_people, group = county, color = county)) +
  ggtitle(glue("ICU Patients with COVID-19 <span style='font-size:14pt'>({ma_n} Day Moving Average)</span>")) +
#          subtitle = glue("{ma_n} Day Moving Average")) +
  theme(
    plot.title = element_markdown()
  ) +
 gglayers +
  ylab(glue("ICU Patients with COVID-19\nper {comma(per_n_people)} People")) +
  annotate("rect",
           xmin = if_else(min(icu_plot_data$date) < sah_start, sah_start, min(icu_plot_data$date)),
           xmax = sah_end, ymin = -Inf, ymax = Inf, alpha = sah_alpha) +
    annotate("text", y = 51, x = sah_end+8, label = "Stay at Home\nOrder Ended")


# Deaths
deaths_plot_data <- cases_tidy %>% 
  filter(name == "newcountdeaths") %>% 
  group_by(county) %>%
  mutate(value = runMean(value, ma_n)) %>% 
  drop_na() %>%
filter(date >= min(hospitalizations_plot_data$date))

deaths_plot <- deaths_plot_data %>% 
  ggplot(aes(date, value / population * per_n_people, group = county, color = county)) +
  ggtitle(glue(" New Daily Deaths due to COVID-19 <span style='font-size:14pt'>({ma_n} Day Moving Average)</span>")) +
#          subtitle = glue("{ma_n} Day Moving Average")) +
  theme(
    plot.title = element_markdown()
  ) +
  gglayers +
  ylab(glue("New Daily Deaths due to COVID-19\nper {comma(per_n_people)} People")) +
  annotate("rect",
           xmin = if_else(min(deaths_plot_data$date) < sah_start,
                          sah_start,
                          min(deaths_plot_data$date)),
           xmax = sah_end, ymin = -Inf, ymax = Inf, alpha = sah_alpha) +
    annotate("text", y = 3, x = sah_end+8, label = "Stay at Home\nOrder Ended")

# Cases
cases_plot_data <- cases_tidy %>% 
  filter(name == "newcountconfirmed") %>% 
  group_by(county) %>%
  mutate(value = runMean(value, ma_n)) %>% 
  drop_na() %>%
filter(date >= min(hospitalizations_plot_data$date))

cases_plot <- cases_plot_data %>% 
  ggplot(aes(date, value / population * per_n_people, group = county, color = county)) +
  ggtitle(glue("New Daily COVID-19 Cases <span style='font-size:14pt'>({ma_n} Day Moving Average)</span>")) +
#          subtitle = glue("{ma_n} Day Moving Average")) +
  theme(
    plot.title = element_markdown()
  ) +
  gglayers +
  ylab(glue("New Daily Confirmed COVID-19 Cases\nper {comma(per_n_people)} People")) +
    annotate("rect",
           xmin = if_else(min(cases_plot_data$date) < sah_start,
                          sah_start,
                          min(cases_plot_data$date)),
           xmax = sah_end, ymin = -Inf, ymax = Inf, alpha = sah_alpha) +
  annotate("text", y = 250, x = sah_end+8, label = "Stay at Home\nOrder Ended")
```


<div class = "row">
<div class = "col-md-6">
```{r hospitalizations_plot}
watermark(hospitalizations_plot)
```
</div>
<div class = "col-md-6">
```{r icu_plot}
watermark(icu_plot)
```
</div>
</div>
<div class = "row">
<div class = "col-md-6">
```{r cases_plot}
watermark(cases_plot)
```
</div>
<div class = "col-md-6">
```{r deaths_plot}
watermark(deaths_plot)
```
</div>
</div>

Data collected from the [California Open Data Portal](https://data.ca.gov/group/covid-19).

Last updated on `r Sys.Date()` 

Last available date in the [California Open Data Portal](https://data.ca.gov/group/covid-19) is `r as.Date(max(hosp_tidy$date, cases_tidy$date))`.

<!-- Last available date in the [California Open Data Portal](https://data.ca.gov/group/covid-19) is `r as.Date(max(resources$last_modified[resources$name %in% c("COVID-19 Cases", "COVID-19 Testing", "Hospitals By County")]))`. -->
