---
title: "COVID-19 Maps by UCI Statistics"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<br>
<br>

### Fraction of positive COVID-19 tests mapped to OC zip codes

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.align = "center",
  message = FALSE,
  warning = FALSE
)
```


```{r libraries}
library(here)

source(here("code", "map-functions.R"))
```


```{r generate-pos-map}
pos_covid_zip_data <- readRDS(here("data", "pos_map_data.rds"))

date_seq <- zoo::as.yearmon(
  seq(as.Date("2020-03-01"), pos_covid_zip_data$max_date_in_data, by = "months"), 
  "%m/%Y"
)

gen_map_gif(
  plot_data = pos_covid_zip_data$pos_plot_data, 
  socal_shp_file = here("data/shape-files/socal-zip", "Zipcode_boundary_scag_2009.shp"), 
  ca_shp_file = here("data/shape-files/ca-counties", "cnty19_1.shp"), 
  legend_label = pos_covid_zip_data$pos_legend_label, 
  month_seq = date_seq, 
  var_type = "pos"
)
```


```{r display-pos-map}
htmltools::includeHTML(here("docs", "pos-map-gif.html"))
```


Data provided by the [Orange County Health Care Agency](https://www.ochealthinfo.com).  
Most recent date in data used was `r pos_covid_zip_data$max_date_in_data`.  
Last updated on `r lubridate::today()`.
